name: Run Blog Bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY:       ${{ secrets.OPENAI_API_KEY }}
      CONFLUENCE_API_USER:  ${{ secrets.CONFLUENCE_API_USER }}
      CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
      NAVER_CLIENT_ID:      ${{ secrets.NAVER_CLIENT_ID }}
      NAVER_CLIENT_SECRET:  ${{ secrets.NAVER_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check openai version
        run: pip show openai

      - name: Run blog bot
        run: python blog_bot.py
