name: Weekly Blog Bot

on:
  schedule:
    # 매주 월요일 07:00 KST  (UTC 일 22:00)
    - cron: '0 22 * * 0'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'
  NAVER_CLIENT_ID:      ${{ secrets.NAVER_CLIENT_ID }}
  NAVER_CLIENT_SECRET:  ${{ secrets.NAVER_CLIENT_SECRET }}
  CONFLUENCE_API_USER:  ${{ secrets.CONFLUENCE_API_USER }}
  CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
  OPENAI_API_KEY:       ${{ secrets.OPENAI_API_KEY }}

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17          # konlpy용 Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run blog bot
      run: python blog_bot.py        # ← 파일명만 수정
